[package]
name = "slightjs-engine"
version = "0.1.0"
edition = "2021"
authors = [ "Dan Chiarlone" ]

[lib]
crate-type = [ "cdylib" ]

[dependencies]
anyhow = "1"
quickjs-wasm-rs = "0.1"
once_cell = "1.4"
send_wrapper = "0.6"